src/forms.py
from flask_wtf import Form
from wtforms import StringField, PasswordField, validators
from wtforms.validators import DataRequired


class RegisterForm(Form):
    """
    Register Form
    """
    username = StringField(label="username", validators=[validators.Length(min=4, max=25)])
    email = StringField(label="E-mail", validators=[validators.Length(min=4, max=25)])
    password = PasswordField(label='Password', validators=[
                    DataRequired()
                ])


class LoginForm(Form):
    """
    Login Form
    """
    email = StringField(label="E-mail", validators=[validators.Length(min=4, max=25)])
    password = PasswordField(label='Password', validators=[
                    DataRequired()
                ])

src/__init__.py
# import os
# from flask import Flask
# from flask_login import LoginManager
# from flask_sqlalchemy import SQLAlchemy
# from flask_bcrypt import Bcrypt
#
# app = Flask(__name__)
#
# cur_path = os.path.dirname(os.path.abspath(__file__))
# par_path = os.path.join(cur_path, os.pardir)
#
# login_manager = LoginManager()
# login_manager.init_app(app)
#
# db = SQLAlchemy(app)
# bcrypt = Bcrypt(app)
#
# app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///' + par_path + '/thrudata.sqlite3'
# app.config['SECRET_KEY'] = "1254sd15gfrf1edewg1er5fdfedfedfeefe_ed"
# app.config['DEBUG'] = False
#
#
# from src.views import main_blueprint
#
#
# app.register_blueprint(main_blueprint)
#
#
# from src.db_model import User
#
#
# @login_manager.user_loader
# def load_user(user_id):
#     return User.query.filter(User.id == int(user_id)).first()

src/views.py
from flask import render_template, Response, request, redirect, url_for, Blueprint, flash
from flask_login import login_required, login_user, logout_user
from src.forms import RegisterForm, LoginForm
from src import db, bcrypt, login_manager
from src.db_model import User
from src.video_feed import VideoFeed

from utils.constant import VIDEO_SRC


main_blueprint = Blueprint('main', __name__, )
vif = VideoFeed(stream_src=VIDEO_SRC)


@main_blueprint.route('/')
@login_required
def index():
    """
    Returns 'index.html' page in route '/'
    :return:
    """
    return render_template('index.html')


@main_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    """
    Returns 'register.html' page in route '/register'
    Redirects 'login.html' page after stored new username and password when request method is post.
    :return:
    """
    register_form = RegisterForm(request.form)
    if request.method == 'POST' and register_form.validate_on_submit():
        user = User(register_form.username.data, register_form.email.data,
                    bcrypt.generate_password_hash(register_form.password.data).decode('utf - 8'))
        db.session.add(user)
        db.session.commit()

        return redirect(url_for('main.login'))
    return render_template('register.html', form1=register_form)


@main_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    """
    Returns 'login.html' page in route '/login'.
    Redirects the 'index.html' page or next url when login is successful.
    :return:
    """
    login_form = LoginForm(request.form)
    if request.method == 'POST' and login_form.validate():
        user = User.query.filter_by(email=login_form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, login_form.password.data):
            login_user(user)
            next = request.args.get('next')
            return redirect(next or url_for('main.index'))

        else:
            flash('Invalid email and/or password.', 'danger')
            return render_template('login.html', login_form=login_form)

    return render_template('login.html', login_form=login_form)


@main_blueprint.route('/logout')
@login_required
def logout():
    """
    Returns 'login.html' page after user is logged out.
    :return:
    """
    logout_user()
    flash('You were logged out.', 'success')
    return redirect(url_for('main.login'))


def gen():
    """
    Start the thread to receive the streaming data from socket server and returns the image processed.
    :return:
    """
    vif.start()
    while True:
        # frame = None
        frame = vif.proc_streaming_marked()
        if frame is not None:
            yield (b'--frame\r\n'
                   b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n\r\n')
        else:
            vif.stop()


@main_blueprint.route('/video_feed')
@login_required
def video_feed():
    """
    Returns the image data as bytes.
    :return:
    """
    return Response(gen(),
                    mimetype='multipart/x-mixed-replace; boundary=frame')


@login_manager.unauthorized_handler
def unauthorized_callback():
    """
    Redirects the login page when user is unauthorized.
    :return:
    """
    return redirect('/login?next=' + request.path)

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>ThruData v1.0</title>

    <link href="/static/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/vendor/metisMenu/metisMenu.min.css" rel="stylesheet">
    <link href="/static/dist/css/sb-admin-2.css" rel="stylesheet">
    <link href="/static/vendor/morrisjs/morris.css" rel="stylesheet">
    <link href="/static/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="https://vjs.zencdn.net/7.0/video-js.min.css" rel="stylesheet">
    <script src="https://vjs.zencdn.net/7.0/video.min.js"></script>
</head>

<body>

    <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-left: 10px;margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">ThruData</a>
            </div>
            <!-- /.navbar-header -->

            <ul class="nav navbar-top-links navbar-right">
                <li><a href="/logout"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                </li>

            </ul>
            <!-- /.navbar-top-links -->
        </nav>

        <div>
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header" style="margin-left: 20px">ThruData</h1>
                    <div class="row">
                        {% block content %}
                        {% endblock %}
                    </div>
                </div>
            </div>
        </div>

        {% include 'footer.html' %}

    </div>
    <script src="/static/vendor/jquery/jquery.min.js"></script>
    <script src="/static/vendor/bootstrap/js/bootstrap.min.js"></script>
    <script src="/static/vendor/metisMenu/metisMenu.min.js"></script>
    <script src="/static/dist/js/sb-admin-2.js"></script>
    {%block script%}
    {%endblock%}
</body>

</html>

src/templates/footer.html
<!-- Begin Footer -->
<footer class="footer">
    <div class="container">
    <!-- Copyright -->
    <div class="row">
        <hr>
        <div class="col-sm-11 col-xs-10">
            <p class="copyright">© 2018 All rights reserved.</p>
        </div>
        <div class="col-sm-1 col-xs-2 text-right">
            <a href="#" class="scroll-top">
                <div class="footer-scrolltop-holder"><span class="ion-ios7-arrow-up footer-scrolltop"></span>
                </div>
            </a>
        </div>
    </div>
</div>
</footer>

src/templates/index.html
{% extends "base.html" %}
{%block content %}
<div class="container">
    <div class="col-lg-8">
        <img id="bg" src="{{ url_for('main.video_feed') }}" width="100%" height="120%">
    </div>

</div>
{%endblock%}

src/templates/login.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="This is Demo System for object detection">
    <meta name="author" content="Evander Jones">
    <title>ThruData v1.0</title>

    <link href="/static/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/vendor/metisMenu/metisMenu.min.css" rel="stylesheet">
    <link href="/static/dist/css/sb-admin-2.css" rel="stylesheet">
    <link href="/static/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">

</head>

<body>

    <div class="container">
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                <div class="login-panel panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">Please Sign In</h3>
                    </div>
                    <div class="panel-body">
                        <form role="form" method="POST">
                            {{ login_form.csrf_token }}
                            <fieldset>
                                <div class="form-group">
                                    {{ login_form.email(class="form-control", placeholder="E-mail", class_='required') }}
                                </div>
                                <div class="form-group">
                                    {{ login_form.password(class="form-control", placeholder="Password", class_='required') }}
                                </div>
                                <!-- Change this to a button or input when using this as a form -->
                                <button type="submit" href="/" class="btn btn-lg btn-success btn-block">Login</button>
                            </fieldset>
                        </form>
                        <br/>
                        <br/>
                        <a href="/register" class="btn btn-lg btn-default btn-block">Register</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="/static/vendor/jquery/jquery.min.js"></script>
    <script src="/static/vendor/bootstrap/js/bootstrap.min.js"></script>
    <script src="/static/vendor/metisMenu/metisMenu.min.js"></script>
    <script src="/static/dist/js/sb-admin-2.js"></script>
</body>

</html>

src/templates/register.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="This is Demo System for object detection">
    <meta name="author" content="Evander Jones">
    <title>ThruData v1.0</title>

    <link href="/static/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/vendor/metisMenu/metisMenu.min.css" rel="stylesheet">
    <link href="/static/dist/css/sb-admin-2.css" rel="stylesheet">
    <link href="/static/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">

</head>

<body>

    <div class="container">
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                <div class="login-panel panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">Please Register</h3>
                    </div>
                    <div class="panel-body">
                        <form role="form" method="POST">
                            {{ form1.csrf_token }}
                            <fieldset>
                                <div class="form-group">
                                    {{ form1.username(class="form-control", placeholder="Username", class_='required') }}
                                </div>
                                <div class="form-group">
                                    {{ form1.email(class="form-control", placeholder="E-mail", class_='required') }}
                                </div>
                                <div class="form-group">
                                    {{ form1.password(class="form-control", placeholder="Password", class_='required') }}
                                </div>
                                <!-- Change this to a button or input when using this as a form -->
                                <button type="submit" class="btn btn-lg btn-success btn-block">Register</button>
                            </fieldset>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="/static/vendor/jquery/jquery.min.js"></script>
    <script src="/static/vendor/bootstrap/js/bootstrap.min.js"></script>
    <script src="/static/vendor/metisMenu/metisMenu.min.js"></script>
    <script src="/static/dist/js/sb-admin-2.js"></script>
</body>

</html>